// Scaffold generated by home_widget. Adjust the widget for your needs.
package com.xiongsircool.aurora.mobile

import es.antonborri.home_widget.HomeWidgetGlanceWidgetReceiver

class AuroraHomeWidgetReceiver : HomeWidgetGlanceWidgetReceiver<AuroraHomeWidget>() {
  override val glanceAppWidget = AuroraHomeWidget()
}
