"""Add title_translations

Revision ID: 2ee599331b61
Revises: 774a0dde0900
Create Date: 2026-01-20 12:31:52.902162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '2ee599331b61'
down_revision: Union[str, Sequence[str], None] = '774a0dde0900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("entries")}
    if "title_translations" not in columns:
        op.add_column('entries', sa.Column('title_translations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'title_translations')
    # ### end Alembic commands ###
